### ISSUE TITLE
Bug with at-rule and sass (Cannot read properties of undefined)

### ISSUE THREAD

**Issue by Rekwian** [ota-meshi/stylelint-config-recommended-vue#50] opened 2023-07-08 07:17 UTC
Hello

i have this error when i use stylelint with sass and stylelint-config-recommended-vue
> TypeError: Cannot read properties of undefined (reading 'start') at LocalFixer.node 

here is my vue file
```vue
<template lang="pug">
div(class="toto") toto
</template>

<style lang="sass">
.toto
  color: red
  background-color: blue

@media (prefers-color-scheme: dark)
  .toto
    color: green
</style>
```
my stylelint config
```javascript
module.exports = {
  extends: [
    'stylelint-scss',
    'stylelint-config-recommended-scss',
    'stylelint-config-recommended-vue',
  ],
  plugins: [
    'stylelint-scss',
    'stylelint-order',
  ],
  rules: {
    'at-rule-no-unknown': null,
    'order/order': [
      'custom-properties',
      'declarations',
    ],
    'order/properties-alphabetical-order': true,
    'scss/at-rule-no-unknown': true,
    'scss/no-global-function-names': null,
  },
};
```
and my devDependencies
```
  "@nuxt/devtools": "latest",
  "@types/node": "^18",
  "nuxt": "^3.6.2",
  "postcss-html": "^1.5.0",
  "postcss-sass": "^0.5.0",
  "pug": "^3.0.2",
  "sass": "^1.63.6",
  "stylelint": "^15.10.1",
  "stylelint-config-recommended-scss": "^12.0.0",
  "stylelint-config-recommended-vue": "^1.4.0",
  "stylelint-order": "^6.0.3",
  "stylelint-scss": "^5.0.1"
```

When i set my at-rule in a mixin in another file and import them, it works but no check into include

**Comment by ota-meshi** [comment] 2023-07-08 07:48
I'm not familiar with Sass.
Could you provide a minimal repository where issue can be reproduced?

**Comment by Rekwian** [comment] 2023-07-08 08:03
Yes : https://github.com/Rekwian/friendly-octo-spoon/tree/main

**Comment by ota-meshi** [comment] 2023-07-08 08:53
The error seems to be caused by the absence of `node.source` in `@media (prefers-color-scheme: dark)` node.
It's possible to get around the error with `postcss-html`, but `stylelint` throws an error when it encounters a node that doesn't have a `node.source`.
https://github.com/stylelint/stylelint/blob/cefd26769a9995d0e7484cd9f0d0bab83e7dc8d4/lib/utils/nodeContextLookup.js#L23

I think you should ask `postcss-sass` repo for a fix it.

**Comment by Rekwian** [comment] 2023-07-08 09:17
I opened an issue, but it seems to be unmaintained 😢.
I don't close this issue cause the bug is still there, but if you think it should be closed, then you can close it.

**Comment by ota-meshi** [comment] 2023-07-08 09:29
I think you probably have the wrong repository.
Checking the postcss-sass repository on npm, I believe the correct repository is https://github.com/AleshaOleg/postcss-sass.
https://www.npmjs.com/package/postcss-sass

> I don't close this issue cause the bug is still there, but if you think it should be closed, then you can close it.

Yeah, I'm closing the issue as there is nothing that can be done with this repository.

**Closed** 2023-07-08 09:30 UTC
Labels: needs repro
