### ISSUE TITLE
Create new release with commit - "Update dependency stylelint to v15"

### ISSUE THREAD

**Issue by websitevirtuoso** [ota-meshi/stylelint-config-recommended-vue#47] opened 2023-04-15 06:37 UTC
3 weeks ago dependency has been updated. Can you create new npm release?

I am getting warning 

➤ YN0060: │ myidealhome@workspace:. provides stylelint (pac2c6) with version 15.4.0, which doesn't satisfy what stylelint-config-recommended-vue and some of its descendants request

I think new release could fix it

**Comment by ota-meshi** [comment] 2023-04-15 13:32
Duplicate of #45

I believe this package already supports Stylelint v15.

**Closed by ota-meshi** 2023-04-15 13:32 UTC

**Comment by websitevirtuoso** [comment] 2023-04-16 17:21
this package updated main branch but release hasn't been created
check this screenshot please
![image](https://user-images.githubusercontent.com/5112918/232329581-579c35c1-476f-4eb7-b5da-98e5f7887cd6.png)

Here my project and file package.json for stylelint-config-recommended-vue

```
{
    "name": "stylelint-config-recommended-vue",
    "version": "1.4.0",
    "description": "The recommended shareable Vue config for Stylelint.",
    "keywords": [
        "stylelint",
        "stylelint-config",
        "recommended",
        "vue"
    ],
    "main": "lib/index.js",
    "files": [
        "lib",
        "scss"
    ],
    "engines": {
        "node": "^12 || >=14"
    },
    "scripts": {
        "test": "mocha \"tests/lib/**/*.js\" --reporter dot --timeout 60000",
        "lint": "eslint .",
        "eslint-fix": "eslint . --fix",
        "version": "npm run test && git add ."
    },
    "dependencies": {
        "semver": "^7.3.5",
        "stylelint-config-html": ">=1.0.0",
        "stylelint-config-recommended": ">=6.0.0"
    },
    "peerDependencies": {
        "stylelint": ">=14.0.0",
        "postcss-html": "^1.0.0"
    },
    "devDependencies": {
        "@ota-meshi/eslint-plugin": "^0.10.0",
        "eslint": "^8.0.0",
        "eslint-config-prettier": "^8.3.0",
        "eslint-plugin-eslint-comments": "^3.2.0",
        "eslint-plugin-json-schema-validator": "^2.0.0",
        "eslint-plugin-jsonc": "^2.0.0",
        "eslint-plugin-node": "^11.1.0",
        "eslint-plugin-prettier": "^4.0.0",
        "eslint-plugin-regexp": "^1.5.0",
        "eslint-plugin-vue": "^8.0.0",
        "eslint-plugin-yml": "^0.14.0",
        "mocha": "^9.1.3",
        "prettier": "^2.4.1",
        "stylelint": "^14.5.0"
    },
    "repository": {
        "type": "git",
        "url": "git+https://github.com/ota-meshi/stylelint-config-recommended-vue.git"
    },
    "author": "Yosuke Ota (https://github.com/ota-meshi)",
    "funding": "https://github.com/sponsors/ota-meshi",
    "license": "MIT",
    "bugs": {
        "url": "https://github.com/ota-meshi/stylelint-config-recommended-vue/issues"
    },
    "homepage": "https://github.com/ota-meshi/stylelint-config-recommended-vue#readme"
}

You can see 2 lines there

        "stylelint": ">=14.0.0",
        "stylelint": "^14.5.0"
        
        I hope it make sense than we need new release for npm with new tag

```
