### ISSUE TITLE
Unsovlable Dependency Tree

### ISSUE THREAD

**Issue by johnnyshankman** [ota-meshi/stylelint-config-recommended-vue#69] opened 2024-01-18 17:10 UTC
```
    "stylelint": "^16.0.0",
    "stylelint-config-recommended": "^14.0.0",
    "stylelint-config-recommended-vue": "^1.6.0",
    "stylelint-config-standard": "^35.0.0",
    "stylelint-config-standard-scss": "^12.0.0",
 ```

```
± |stylelint-16 U:1 ✗| → yarn
yarn install v1.22.21
warning ../package.json: No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "stylelint-config-recommended-vue > stylelint-config-recommended@13.0.0" has incorrect peer dependency "stylelint@^15.10.0".
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
✨  Done in 0.75s.
```

There's no way to solve this. If I put it recommended `stylelint-config-recommended` on v13 then i can't use stylelint 16.

```
yarn install v1.22.21
warning ../package.json: No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > stylelint-config-recommended@13.0.0" has incorrect peer dependency "stylelint@^15.10.0".
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
✨  Done in 0.72s.
```

But if I downgrade to v15 I get:
```
warning " > stylelint-config-standard@35.0.0" has incorrect peer dependency "stylelint@^16.0.0".
warning "stylelint-config-standard > stylelint-config-recommended@14.0.0" has incorrect peer dependency "stylelint@^16.0.0".
warning " > stylelint-config-standard-scss@12.0.0" has incorrect peer dependency "stylelint@^16.0.2".
warning "stylelint-config-standard-scss > stylelint-config-recommended-scss@14.0.0" has incorrect peer dependency "stylelint@^16.0.2".
warning " > stylelint-scss@6.0.0" has incorrect peer dependency "stylelint@^16.0.2".
```

There's no solve unless you support recommended @14 i think.

Otherwise the only working version of this is:
```
    "stylelint": "^15.0.0",
    "stylelint-config-recommended": "^13.0.0",
    "stylelint-config-recommended-vue": "^1.5.0",
    "stylelint-config-standard": "^33.0.0",
    "stylelint-config-standard-scss": "^10.0.0",
    "stylelint-scss": "^5.0.0",
    ```

**Comment by ota-meshi** [comment] 2024-01-19 00:20
duplicate of #69

**Closed by ota-meshi** 2024-01-19 00:20 UTC
