### ISSUE TITLE
Support stylelint 16.x

### ISSUE THREAD

**Issue by mecograph** [ota-meshi/stylelint-config-recommended-vue#67] opened 2023-12-21 15:50 UTC
Is there a plan when stylelint 16 will be officially supported? As of now I get an peer dependency warning when trying to use this package with anything higher than v15.

**Comment by ota-meshi** [comment] 2023-12-21 16:27
Duplicate of https://github.com/ota-meshi/stylelint-config-recommended-vue/issues/63

**Closed by ota-meshi** 2023-12-21 16:27 UTC
